
def class AT:
    SET_FACTORY_DEFINED_CONFIGURATION = 'AT&F'
    GET_CURRENT_CONFIGURATION = 'AT&V'
    SET_DEFAULT_CONFIGURATION = 'ATZ'

    SET_TONE_DIALING = 'ATT'

    CELL_TIME_A = 'AT+CLTS=1'
    CELL_TIME_B = 'AT&W'
    GET_LOCAL_TIME = 'AT+CCLK?'

    SET_GPS_ACTIVE = 'AT+CGNSPWR=1'
    GET_GPS_DATA = 'AT+CGNSINF'
    GET_NTP_SERVER = 'AT+CNTP?'

    GET_COMPLETE_TA_CAPABILITIES_LIST = 'AT+GCAP'
    GET_MANUFACTURER_IDENTIFICATION = 'AT+GMI'
    GET_TA_MODEL_IDENTIFICATION = 'AT+GMM'
    GET_TA_REVISION_IDENTIFICATION_OF_SOFTWARE_RELEASE = 'AT+GMR'
    GET_GLOBAL_OBJECT_IDENTIFICATION = 'AT+GOI'
    GET_TA_SERIAL_NUMBER_IDENTIFICATION = 'AT+GSN'

    DISCONNECT_VOICE_CALL_ONLY = 'AT+HVOIC'

    GET_MANUFACTURER_IDENTIFICATION  = 'AT+CGMI'
    GET_MODEL_IDENTIFICATION = 'AT+CGMM'
    GET_TA_REVISION_IDENTIFICATION_OF_SOFTWARE_RELEASE = 'AT+CGMR'
    GET_PRODUCT_SERIAL_NUMBER_IDENTIFICATION = 'AT+CGSN'

    GET_INTERNATIONAL_MOBILE_SUBSCRIBER_IDENTITY = 'AT+CIMI'
    GET_CURRENT_CALLS_OF_ME = 'AT+CLCC'
